"""add description to products

Revision ID: 04501e6e583c
Revises: 4aa10d832100
Create Date: 2019-04-04 16:03:44.192129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04501e6e583c'
down_revision = '4aa10d832100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
